# Generated by Django 3.2.9 on 2022-06-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=15, verbose_name='Apellido paterno')),
                ('second_last_name', models.CharField(max_length=15, verbose_name='Apellido materno')),
                ('email', models.EmailField(default='@uptapachula.edu.mx', max_length=254, unique=True, verbose_name='Correo')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=50, verbose_name='Género')),
                ('teacher_status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Estatus del docente')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'LABS_TEACHER_CAT',
                'ordering': ['first_name', 'last_name', 'second_last_name'],
            },
        ),
    ]
