# Generated by Django 3.2.9 on 2022-06-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('enrollment', models.IntegerField(primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('name', models.CharField(max_length=120, verbose_name='Nombre(s)')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'LABS_ALUMN_CAT',
            },
        ),
    ]
