# Generated by Django 3.2.9 on 2022-06-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('enrollment', models.IntegerField(primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('first_name', models.CharField(max_length=30, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=15, verbose_name='Apellido Paterno')),
                ('second_last_name', models.CharField(max_length=15, verbose_name='Apellido Materno')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default=None, max_length=50, verbose_name='Género')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo')),
            ],
            options={
                'verbose_name': 'Alumno',
                'verbose_name_plural': 'Alumnos',
                'db_table': 'LABS_ALUMN_CAT',
            },
        ),
    ]
