# Generated by Django 3.2.9 on 2022-06-13 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_program_name', models.CharField(max_length=60, unique=True, verbose_name='Nombre del programa academico')),
                ('homosigla', models.CharField(help_text='Abreviatura del programa academico', max_length=10, unique=True, verbose_name='Holosigla')),
                ('academic_program_name_gdp', models.CharField(max_length=70, unique=True, verbose_name='Nombre programa academico dgp')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'db_table': 'LABS_CAREER_CAT',
            },
        ),
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='<mes y año de inicio> - <mes y año del fin>', max_length=50, unique=True, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(verbose_name='Fecha fin')),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'db_table': 'LABS_CYCLE_CAT',
            },
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2, unique=True, verbose_name='Cuatrimestre')),
            ],
            options={
                'verbose_name': 'Cuatrimestre',
                'verbose_name_plural': 'Cuatrimestres',
                'db_table': 'LABS_QUARTER_CAT',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=15, verbose_name='Descripcion')),
                ('abbreviation', models.CharField(max_length=5, verbose_name='Abreviacion')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'LABS_SHIFT_CAT',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(help_text='Nombre del estado', max_length=20, unique=True, verbose_name='Status')),
                ('description', models.CharField(help_text='Descripción del estado', max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'LABS_STATUS',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('code_subject', models.CharField(blank=True, max_length=20, verbose_name='Clave asignatura')),
                ('credits', models.IntegerField(default=10, verbose_name='Creditos')),
                ('theoretical_hours', models.IntegerField(default=25, verbose_name='Horas teóricas')),
                ('practical_hours', models.IntegerField(default=5, verbose_name='Horas practicas')),
                ('certifiable', models.BooleanField(default=True, verbose_name='Certificable')),
                ('limit_absence', models.IntegerField(default=4, verbose_name='Limite faltas')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quarter', verbose_name='Cuatrimestre')),
                ('status', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'LABS_SUBJECT_CAT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(verbose_name='Fecha fin')),
                ('vacational_start_date', models.DateField(verbose_name='Fecha inicio de periodo vacacional')),
                ('vacational_end_date', models.DateField(verbose_name='Fecha fin de periodo vacacional')),
                ('cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cycle', verbose_name='Ciclo')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Periodo',
                'verbose_name_plural': 'Periodos',
                'db_table': 'LABS_PERIOD_CAT',
            },
        ),
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Nombre de la modalidad', max_length=250, unique=True, verbose_name='Descripción')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Modalidad',
                'verbose_name_plural': 'Modalidades',
                'db_table': 'LABS_MODALITY_CAT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=30, verbose_name='Grupo')),
                ('code', models.CharField(max_length=32, verbose_name='Clave')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.career', verbose_name='Carrera')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.period', verbose_name='Periodo')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quarter', verbose_name='Cuatrimestre')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.shift', verbose_name='Turno')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'LABS_GROUP_CAT',
            },
        ),
        migrations.AddField(
            model_name='cycle',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='career',
            name='modality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modality', verbose_name='Modalidad'),
        ),
        migrations.AddField(
            model_name='career',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.status', verbose_name='Estado'),
        ),
    ]
